# Generated by Django 4.1.1 on 2022-09-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exampleModel',
        ),
    ]
