# Generated by Django 4.1.1 on 2022-10-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcategorymodel',
            name='subject_id',
            field=models.IntegerField(default=1),
        ),
    ]
