# Generated by Django 4.1.1 on 2022-09-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleName', models.CharField(max_length=255)),
                ('titleIcon', models.CharField(max_length=255)),
                ('contentId', models.IntegerField()),
            ],
        ),
    ]
