# Generated by Django 4.1.1 on 2022-09-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('ans', models.CharField(max_length=255)),
                ('levelId', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
