# Generated by Django 4.1.1 on 2022-10-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='subjectNameFench',
            field=models.CharField(default='Any', max_length=255),
        ),
    ]
